name: Node.js CI

on:
  pull_request:
    types: [opened]

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install packages
        run: npm ci
  test:
    name: Test
    steps:
      - name: Mutation testing
        run: npm run testm