name: Scheduler Engine CI

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install packages
        run: npm ci
  test:
    steps:
      - name: Mutation testing
        run: npm run testm